---
- hosts: localhost
  connection: local
  vars:
    the_user: "{{ ansible_user_id }}"
  tasks:
  - name: install packages
    become: yes
    package:
      name:
      - curl
      - git
      - htop
      - zsh
      - neofetch
      state: latest
      update_cache: yes

  - name: Install ohmyzsh unattended
    shell: >
      wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh &&
      sh install.sh --unattended

  - name: Clone Powerlevel10k theme
    command: "git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k"

  - name: Clone zsh-autosuggestions
    command: "git clone https://github.com/zsh-users/zsh-autosuggestions.git ~/.oh-my-zsh/plugins/zsh-autosuggestions"

  - name: Clone zsh-syntax-highlightingd
    command: "git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/plugins/zsh-syntax-highlighting"

  - name: copy .zshrc file
    copy:
     src: files/zshrc
     dest: ~/.zshrc

  - name: copy p10k.zsh file
    copy:
     src: files/p10k.zsh
     dest: ~/.p10k.zsh

  - name: change user shell to zsh 
    become: yes
    user:
      name: "{{ the_user }}"
      shell: /bin/zsh
